name: 'Dialogflow CI/CD'

on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [app_engine_node]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
          path: 'dialogflow/DialogflowTest.zip'
          destination: 'gs://sample-bucket-en-service-provider-chatbot-test/dialogflow1.zip'


